### ISSUE TITLE
No module named pgxnclient.cli

### ISSUE THREAD

**Issue by Karlodun** [pgxn/pgxnclient#32]
fresh install in WSL. Any easy solutions?
As far as I understand the reference goes to pgxnclient/cli.py, and I can fix this.... but to fix it every time I am on a new computer or updating/reinstalling....

```
 # pgxn help --libexec
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pgxnclient/libexec/pgxn-help", line 10, in <module>
    from pgxnclient.cli import script
ImportError: No module named pgxnclient.cli
```

**Comment by arkangle** [comment]
How did  you fix the reference issue?

**Comment by kspoon01** [comment]
I ran into the same issue, how did you fix this issue?

**Comment by dvarrazzo** [comment]
Can't reproduce the problem. I added a test to verify it. The problem might have been solved by the fact that now the codebase is 2 and 3 compatible. So it should be fixed in release 1.3. however I'd be interested to know how the module was installed. Thank you.

**Comment by shatteringlass** [comment]
I have encountered this issue with the module installed today via pip3.

**Comment by fake-name** [comment]
I just hit this issue. 

The problem is that the `pgxnclient` script is invoking the wrong python.

Basically, I have pgxnclient installed in python3. However, `pgxnclient/cli.py` invokes some of the subscripts (`libexec/pgxn-install`, in my case) via `os.execv()`, which then uses the shebang line in the subcommand to chose the runtime interpreter. 

The commands in `libexec/*` all have the shebang line of `#!/usr/bin/env python`, which then invokes python **2**, and immediately fails because it's the wrong python.

**Comment by dvarrazzo** [comment]
Will look into it.

**Comment by fake-name** [comment]
Cool!

**Comment by dvarrazzo** [comment]
@fake-name Np, but I should wrap a release sooner than later... Have to dust off and automate integration tests.

**Comment by fake-name** [comment]
So this is still an issue, and I don't exactly fancy hand-fixing all the various sub-scripts. Any chance of a release?
